namespace Wacton.Colonies.Ancillary
{
    public class Coordinate
    {
        public readonly int X;
        public readonly int Y;

        public Coordinate(int x, int y)
        {
            this.X = x;
            this.Y = y;
        }

        private bool Equals(Coordinate other)
        {
            return this.X == other.X && this.Y == other.Y;
        }

        /* Equals & GetHashCode overrides generated by resharper 
         * object comparison was required by EcosystemLogic */
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj))
            {
                return false;
            }
            if (ReferenceEquals(this, obj))
            {
                return true;
            }
            if (obj.GetType() != this.GetType())
            {
                return false;
            }
            return Equals((Coordinate)obj);
        }

        public override int GetHashCode()
        {
            unchecked
            {
                return (this.X * 397) ^ this.Y;
            }
        }

        public override string ToString()
        {
            return string.Format("({0}, {1})", this.X, this.Y);
        }
    }
}
